name: Docker/ARGO CI/CD

on:
  push:
    branches: [ main ]
jobs:
  Build-Push-Docker:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            name: changing to the repo where the dockerfile is located
            with:
              repository: 'USU-WebApp/Capstone-Project-work'
              ref: main
              token: ${{ secrets.GIT_PASSWORD }}
              path: ./repo-with-dockerfile
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          -
            name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          -
            name: Build and push
            uses: docker/build-push-action@v4
            with:
              context: ./repo-with-dockerfile
              platforms: linux/amd64,linux/arm64
              push: true
              tags: badejotobi/usu:0.${{ github.run_number }}
